<a href="https://colab.research.google.com/github/Rashedrahmann/learnig-log/blob/Rashed/exam2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Answer Question 1(1)**

In [64]:
import pandas as pd
import numpy as np

In [65]:
pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

In [66]:

raw=pd.read_excel('/content/Churn.xlsx')

In [67]:
df=raw.copy()

In [68]:
df.head(20)

,CustomerID,Age,Gender,Region,PlanType,MonthlyCharges,TenureMonths,SupportTickets,AvgMonthlyUsageHours,ContractType,PaymentMethod,AutoPay,SatisfactionScore,LastLoginDays,ReferralCount,DeviceCount,Churn
0,C0001,__35__,Male,South,Basic,16.62,2,5,__27.0__,Quarterly,Card,Yes,4,26,0,1,0
1,C0002,26,Male,North,Standard,46.23,__4__,0,46.1,Monthly,UPI,Yes,5,11,0,2,1
2,C0003,31,Female,North,Standard,43.04,32,0,27.2,NaN,UPI,Yes,7,6,2,3,0
3,C0004,34,Male,East,Basic,29.19,20,4,25.1,Monthly,Bank Transfer,Yes,4,19,0,4,0
4,C0005,38,Female,North,Basic,24.95,1,4,49,Monthly,Cash,No,3,25,0,3,1
5,C0006,36,Female,East,Standard,47.99,11,0,36.8,3,Card,Yes,8,0,2,3,0
6,C0007,28,Female,West,Standard,37.51,64,2,40.2,Quarterly,NaN,Yes,5,10,2,3,0
7,C0008,58,Male,Central,Standard,37.32,13,4,50.6,3,Bank Transfer,Yes,5,13,4,2,0
8,C0009,26,Male,East,Premium,69.6,33,1,57.3,Yearly,Cash,Yes,6,1,2,2,0
9,C0010,23,Male,Central,Standard,43.56,5,0,37.6,Monthly,Card,No,5,0,0,2,0
10,C0011,29,Male,South,Basic,27.07,23,5,42.2,Monthly,Card,Yes,4,20,0,1,0
11,C0012,29,Female,West,Basic,15.25,2,3,46.1,Monthly,UPI,No,6,9,0,2,0
12,C0013,37,Male,West,Basic,__23.2__,12,5,37.7,Yearly,UPI,NaN,4,3,1,2,0
13,C0014,37,Female,West,Premium,83.14,4,4,53.1,Yearly,UPI,Yes,4,0,"""""",2,0
14,C0015,39,Male,Central,Basic,23.21,7,7,44.1,Yearly,Bank Transfer,Yes,1,18,1,2,0
15,C0016,18,Female,Central,Standard,52.84,18,0,"""49.1""",Monthly,Cash,Yes,6,0,0,3,0
16,C0017,29,Male,West,Standard,54.22,15,4,"""49.0""",Monthly,__value__,Yes,__6__,11,0,3,0
17,C0018,26,Female,Central,Basic,39.74,31,NaN,56.5,Yearly,Card,Yes,__7__,12,0,3,0
18,C0019,41,Male,West,Basic,28.87,43,8,44.9,Yearly,Card,Yes,7,27,1,3,0
19,C0020,32,Female,South,Standard,40.54,33,1,38.7,Monthly,Card,No,7,0,1,2,0

In [69]:
df.isnull().sum()

CustomerID                0
Age                      72
Gender                   68
Region                   52
PlanType                 55
MonthlyCharges          112
TenureMonths             60
SupportTickets           66
AvgMonthlyUsageHours     98
ContractType             69
PaymentMethod            54
AutoPay                  60
SatisfactionScore        78
LastLoginDays            47
ReferralCount            25
DeviceCount              32
Churn                     0
dtype: int64

In [70]:
df['Age'].isna().sum()

np.int64(72)

In [71]:
df['Age'].isna().mean()

np.float64(0.02057142857142857)

In [72]:
df.head(10)

,CustomerID,Age,Gender,Region,PlanType,MonthlyCharges,TenureMonths,SupportTickets,AvgMonthlyUsageHours,ContractType,PaymentMethod,AutoPay,SatisfactionScore,LastLoginDays,ReferralCount,DeviceCount,Churn
0,C0001,__35__,Male,South,Basic,16.62,2,5,__27.0__,Quarterly,Card,Yes,4,26,0,1,0
1,C0002,26,Male,North,Standard,46.23,__4__,0,46.1,Monthly,UPI,Yes,5,11,0,2,1
2,C0003,31,Female,North,Standard,43.04,32,0,27.2,NaN,UPI,Yes,7,6,2,3,0
3,C0004,34,Male,East,Basic,29.19,20,4,25.1,Monthly,Bank Transfer,Yes,4,19,0,4,0
4,C0005,38,Female,North,Basic,24.95,1,4,49,Monthly,Cash,No,3,25,0,3,1
5,C0006,36,Female,East,Standard,47.99,11,0,36.8,3,Card,Yes,8,0,2,3,0
6,C0007,28,Female,West,Standard,37.51,64,2,40.2,Quarterly,NaN,Yes,5,10,2,3,0
7,C0008,58,Male,Central,Standard,37.32,13,4,50.6,3,Bank Transfer,Yes,5,13,4,2,0
8,C0009,26,Male,East,Premium,69.6,33,1,57.3,Yearly,Cash,Yes,6,1,2,2,0
9,C0010,23,Male,Central,Standard,43.56,5,0,37.6,Monthly,Card,No,5,0,0,2,0

In [73]:
df['Age'].isna().sum()

np.int64(72)

In [74]:
df['Age'] = df['Age'].astype(str).str.strip().str.replace(r'[^a-zA-Z0-9]','',regex=True)

In [75]:
df['Age'].isna().sum()

np.int64(0)

In [76]:
df.head()

,CustomerID,Age,Gender,Region,PlanType,MonthlyCharges,TenureMonths,SupportTickets,AvgMonthlyUsageHours,ContractType,PaymentMethod,AutoPay,SatisfactionScore,LastLoginDays,ReferralCount,DeviceCount,Churn
0,C0001,35,Male,South,Basic,16.62,2,5,__27.0__,Quarterly,Card,Yes,4,26,0,1,0
1,C0002,26,Male,North,Standard,46.23,__4__,0,46.1,Monthly,UPI,Yes,5,11,0,2,1
2,C0003,31,Female,North,Standard,43.04,32,0,27.2,NaN,UPI,Yes,7,6,2,3,0
3,C0004,34,Male,East,Basic,29.19,20,4,25.1,Monthly,Bank Transfer,Yes,4,19,0,4,0
4,C0005,38,Female,North,Basic,24.95,1,4,49,Monthly,Cash,No,3,25,0,3,1

In [77]:
df['TenureMonths'] = df['TenureMonths'].astype(str).str.strip().str.replace(r'[^a-zA-Z0-9]','',regex=True)

In [78]:
df['AvgMonthlyUsageHours'] = df['AvgMonthlyUsageHours'].astype(str).str.strip().str.replace(r'[^a-zA-Z0-9]','',regex=True)

In [79]:
dupe_customerid = df.duplicated(['CustomerID']).sum()

In [80]:
dupe_customerid

np.int64(0)

In [81]:
dupe_Age=df.duplicated(['Age']).sum()
dupe_Age

np.int64(3445)

In [82]:
df['PaymentMethod'] = df['PaymentMethod'].fillna(df['PaymentMethod'].mode())

In [83]:
df.head()

,CustomerID,Age,Gender,Region,PlanType,MonthlyCharges,TenureMonths,SupportTickets,AvgMonthlyUsageHours,ContractType,PaymentMethod,AutoPay,SatisfactionScore,LastLoginDays,ReferralCount,DeviceCount,Churn
0,C0001,35,Male,South,Basic,16.62,2,5,270,Quarterly,Card,Yes,4,26,0,1,0
1,C0002,26,Male,North,Standard,46.23,4,0,461,Monthly,UPI,Yes,5,11,0,2,1
2,C0003,31,Female,North,Standard,43.04,32,0,272,NaN,UPI,Yes,7,6,2,3,0
3,C0004,34,Male,East,Basic,29.19,20,4,251,Monthly,Bank Transfer,Yes,4,19,0,4,0
4,C0005,38,Female,North,Basic,24.95,1,4,49,Monthly,Cash,No,3,25,0,3,1

In [84]:
df['ContractType'] = df['ContractType'].fillna(df['ContractType'].mode())

In [85]:
duplicates = df[df.duplicated(keep=False)]

In [86]:
customer_id_duplicates = df[df.duplicated("CustomerID", keep=False)]

In [87]:
customer_id_duplicates

Empty DataFrame
Columns: [CustomerID, Age, Gender, Region, PlanType, MonthlyCharges, TenureMonths, SupportTickets, AvgMonthlyUsageHours, ContractType, PaymentMethod, AutoPay, SatisfactionScore, LastLoginDays, ReferralCount, DeviceCount, Churn]
Index: []

In [88]:
con_duplicates=df.duplicated().sum()

In [89]:
con_duplicates

np.int64(0)

In [90]:
customer_id_duplicates = df[df.duplicated("CustomerID", keep=False)]

customer_id_duplicates

Empty DataFrame
Columns: [CustomerID, Age, Gender, Region, PlanType, MonthlyCharges, TenureMonths, SupportTickets, AvgMonthlyUsageHours, ContractType, PaymentMethod, AutoPay, SatisfactionScore, LastLoginDays, ReferralCount, DeviceCount, Churn]
Index: []

**Answer question1(2)**

In [91]:
df.head(10)

,CustomerID,Age,Gender,Region,PlanType,MonthlyCharges,TenureMonths,SupportTickets,AvgMonthlyUsageHours,ContractType,PaymentMethod,AutoPay,SatisfactionScore,LastLoginDays,ReferralCount,DeviceCount,Churn
0,C0001,35,Male,South,Basic,16.62,2,5,270,Quarterly,Card,Yes,4,26,0,1,0
1,C0002,26,Male,North,Standard,46.23,4,0,461,Monthly,UPI,Yes,5,11,0,2,1
2,C0003,31,Female,North,Standard,43.04,32,0,272,NaN,UPI,Yes,7,6,2,3,0
3,C0004,34,Male,East,Basic,29.19,20,4,251,Monthly,Bank Transfer,Yes,4,19,0,4,0
4,C0005,38,Female,North,Basic,24.95,1,4,49,Monthly,Cash,No,3,25,0,3,1
5,C0006,36,Female,East,Standard,47.99,11,0,368,3,Card,Yes,8,0,2,3,0
6,C0007,28,Female,West,Standard,37.51,64,2,402,Quarterly,NaN,Yes,5,10,2,3,0
7,C0008,58,Male,Central,Standard,37.32,13,4,506,3,Bank Transfer,Yes,5,13,4,2,0
8,C0009,26,Male,East,Premium,69.6,33,1,573,Yearly,Cash,Yes,6,1,2,2,0
9,C0010,23,Male,Central,Standard,43.56,5,0,376,Monthly,Card,No,5,0,0,2,0

In [93]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Reload original dataset
df = pd.read_excel("Churn.xlsx")

# Find categorical columns
categorical_columns = df.select_dtypes(include=['object']).columns

# Encode categorical columns
for col in categorical_columns:
    df[col] = df[col].astype(str)
    encoder = LabelEncoder()
    df[col] = encoder.fit_transform(df[col])

df.head()

,CustomerID,Age,Gender,Region,PlanType,MonthlyCharges,TenureMonths,SupportTickets,AvgMonthlyUsageHours,ContractType,PaymentMethod,AutoPay,SatisfactionScore,LastLoginDays,ReferralCount,DeviceCount,Churn
0,0,64,1,3,3,349,12,8,664,4,1,3,5,20,1,1,0
1,1,9,1,2,5,1571,83,1,381,3,3,3,6,4,1,2,1
2,2,14,0,2,5,1421,26,1,189,7,3,3,8,40,3,3,0
3,3,17,1,1,3,858,13,7,168,3,0,3,5,12,1,4,0
4,4,21,0,2,3,707,1,7,410,3,2,2,4,19,1,3,1

In [94]:
from sklearn.preprocessing import StandardScaler

# Select numerical columns
numeric_columns = df.select_dtypes(include=['int64', 'float64']).columns

# Exclude CustomerID if it is numeric
numeric_columns = numeric_columns.drop('CustomerID', errors='ignore')

# Create scaler
scaler = StandardScaler()

# Scale numerical features
df[numeric_columns] = scaler.fit_transform(df[numeric_columns])

# Check the result
df.head()

,CustomerID,Age,Gender,Region,PlanType,MonthlyCharges,TenureMonths,SupportTickets,AvgMonthlyUsageHours,ContractType,PaymentMethod,AutoPay,SatisfactionScore,LastLoginDays,ReferralCount,DeviceCount,Churn
0,0,2.856273,0.426474,0.574828,-0.716318,-1.280500,-0.681338,0.587543,2.036038,0.282474,-0.342392,0.616919,-0.433982,0.293520,-0.708702,-0.987787,-0.439679
1,1,-0.852822,0.426474,-0.066312,0.879045,0.270781,2.227811,-1.232970,0.112206,-0.529233,1.246961,0.616919,-0.111079,-0.716503,-0.708702,-0.290197,2.274388
2,2,-0.515632,-0.785101,-0.066312,0.879045,0.080362,-0.107703,-1.232970,-1.193009,2.717596,1.246961,0.616919,0.534728,1.556049,0.332850,0.407392,-0.439679
3,3,-0.313317,0.426474,-0.707452,-0.716318,-0.634345,-0.640364,0.327469,-1.335767,-0.529233,-1.137068,0.616919,-0.433982,-0.211492,-0.708702,1.104982,-0.439679
4,4,-0.043565,-0.785101,-0.066312,-0.716318,-0.826033,-1.132051,0.327469,0.309348,-0.529233,0.452284,-0.702896,-0.756885,0.230394,-0.708702,0.407392,2.274388

In [95]:
df.describe()

,CustomerID,Age,Gender,Region,PlanType,MonthlyCharges,TenureMonths,SupportTickets,AvgMonthlyUsageHours,ContractType,PaymentMethod,AutoPay,SatisfactionScore,LastLoginDays,ReferralCount,DeviceCount,Churn
count,3500.000000,3.500000e+03,3.500000e+03,3.500000e+03,3.500000e+03,3.500000e+03,3.500000e+03,3.500000e+03,3.500000e+03,3.500000e+03,3.500000e+03,3.500000e+03,3.500000e+03,3.500000e+03,3.500000e+03,3.500000e+03,3.500000e+03
mean,1749.500000,-6.090366e-17,-8.323501e-17,-1.177471e-16,-1.086115e-16,1.096266e-16,-8.678772e-17,-6.293379e-17,1.329730e-16,-1.400784e-16,3.045183e-17,1.106417e-16,-1.035362e-16,-1.522592e-18,5.176811e-17,4.567775e-17,-4.060244e-18
std,1010.507298,1.000143e+00,1.000143e+00,1.000143e+00,1.000143e+00,1.000143e+00,1.000143e+00,1.000143e+00,1.000143e+00,1.000143e+00,1.000143e+00,1.000143e+00,1.000143e+00,1.000143e+00,1.000143e+00,1.000143e+00,1.000143e+00
min,0.000000,-1.459765e+00,-7.851006e-01,-1.348592e+00,-3.109363e+00,-1.723542e+00,-1.173025e+00,-1.493044e+00,-2.477829e+00,-2.964355e+00,-1.137068e+00,-3.342526e+00,-2.048498e+00,-9.690092e-01,-1.229478e+00,-1.685377e+00,-4.396788e-01
25%,874.750000,-6.505079e-01,-7.851006e-01,-7.074523e-01,-7.163180e-01,-8.869674e-01,-8.042596e-01,-9.728972e-01,-6.491694e-01,-5.292331e-01,-3.423920e-01,-7.028957e-01,-4.339820e-01,-9.058828e-01,-7.087018e-01,-2.901973e-01,-4.396788e-01
50%,1749.500000,-1.110031e-01,4.264744e-01,-6.631221e-02,8.136352e-02,-5.326659e-03,-2.715986e-01,6.739614e-02,-2.715312e-02,-5.292331e-01,-3.423920e-01,6.169192e-01,-1.110787e-01,-4.008711e-01,-1.879258e-01,-2.901973e-01,-4.396788e-01
75%,2624.250000,4.285017e-01,4.264744e-01,5.748279e-01,8.790451e-01,9.210626e-01,6.708016e-01,5.875428e-01,6.084592e-01,1.094181e+00,1.246961e+00,6.169192e-01,5.347278e-01,6.249339e-01,3.328503e-01,4.073923e-01,-4.396788e-01
max,3499.000000,3.935283e+00,5.272774e+00,3.139388e+00,3.272090e+00,1.573248e+00,2.555602e+00,3.968496e+00,2.246775e+00,3.529303e+00,3.630990e+00,4.576364e+00,4.086664e+00,2.502946e+00,6.582163e+00,6.685699e+00,2.274388e+00